Movie Manager UI/Models/Tmdb/SearchResult.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using MonkeyAsylum.MovieManager.UI.Configuration;

namespace MonkeyAsylum.MovieManager.UI.Models.Tmdb {
	public class SearchResult {

		public int Id {
			get; set;
		}

		public string Title {
			get; set;
		}

		public string PosterPath {
			get; set;
		}

		[Display(Prompt = "yyyy-MM-dd")]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}", ConvertEmptyStringToNull = true)]
		public DateTime ReleaseDate {
			get; set;
		}

		public string Overview {
			get; set;
		}

		public List<int> GenreIds {
			get; set;
		}
		//public bool Adult{get;set;}
		//public string OriginalTitle{get;set;}
		//public string OriginalLanguage{get;set;}
		//public string BackdropPath{get;set;}
		//public number Popularity{get;set;}
		//public int VoteCount{get;set;}
		//public bool Video{get;set;}
		//public number VoteAverage{get;set;}

		public string GetPosterUrl() {
			string Url = TmdbConfiguration.Settings.Images.SecureBaseUrl ?? TmdbConfiguration.Settings.Images.BaseUrl;
			return string.IsNullOrWhiteSpace(Url) || string.IsNullOrWhiteSpace(PosterPath) ? "/cache/movie-placeholder.png" : $"{Url}{TmdbConfiguration.Settings.GetPosterSizeString(500)}{PosterPath}";
		}
	}
}

Movie Manager UI/Models/Tmdb/SearchResults.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MonkeyAsylum.MovieManager.UI.Models.Tmdb {
	public class SearchResults {

		public int Page {
			get; set;
		}

		public List<SearchResult> Results {
			get; set;
		}

		public int TotalResults {
			get; set;
		}
		public int TotalPages {
			get; set;
		}
	}
}

Movie Manager UI/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Operations;
using MonkeyAsylum.MovieManager.Data.Models;
using MonkeyAsylum.MovieManager.UI.Configuration;
using MonkeyAsylum.MovieManager.UI.Models;
using MonkeyAsylum.MovieManager.UI.Models.Tmdb;
using RestSharp;

namespace MonkeyAsylum.MovieManager.UI.Controllers {
	public class MovieController : Controller {

		private readonly MovieCollection _movies = new MovieCollection();

		public ActionResult Default() {
			ViewData["Title"] = "Thumbnail View";
			ViewData["ReturnUrl"] = "_MovieThumbnails";
			return View(_movies);
		}

		public ActionResult ThumbnailView() {
			ViewData["Title"] = "Thumbnail View";
			ViewData["ReturnUrl"] = "_MovieThumbnails";
			return PartialView("_MovieThumbnails", _movies);
		}

		public ActionResult ListView() {
			ViewData["Title"] = "List View";
			ViewData["ReturnUrl"] = "_MovieList";
			return PartialView("_MovieList", _movies);
		}

		public ActionResult DetailListView() {
			ViewData["Title"] = "Details View";
			ViewData["ReturnUrl"] = "_MovieDetailList";
			return PartialView("_MovieDetailList", _movies);
		}

		public ActionResult ViewMovie(string id) {
			Movie target = _movies[id];
			ViewData["Mode"] = "EditMovie";
			ViewBag.AllRatings = GenerateRatingList(target.Rating);
			return PartialView("_MovieView", target);
		}

		[HttpGet]
		public ActionResult AddMovie() {
			Movie target = new Movie();
			ViewData["Mode"] = "AddMovie";
			ViewBag.AllRatings = GenerateRatingList();
			return PartialView("_MovieView", target);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult AddMovie(Movie target, string returnUrl) {
			try {
				if (target.Rating?.Code == null || target.Rating?.Name == null) {
					target.Rating = null;
				}

				if (ModelState.IsValid) {
					_movies.Add(target);
				}
				else {
					ViewData["Mode"] = "AddMovie";
					ViewData["IsInvalid"] = true;
					ViewData["BodyOnly"] = true;
					ViewBag.AllRatings = GenerateRatingList(target.Rating);
					return PartialView("_MovieView", target);
				}
			}
			catch {
				ViewData["Mode"] = "AddMovie";
				ViewData["IsInvalid"] = true;
				ViewData["BodyOnly"] = true;
				ViewBag.AllRatings = GenerateRatingList(target.Rating);
				return PartialView("_MovieView", target);
			}
			ViewData["ReturnUrl"] = returnUrl;
			return PartialView(returnUrl, _movies);
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult EditMovie(Movie target, string returnUrl) {
			try {
				if (target.Rating?.Code == null || target.Rating?.Name == null) {
					target.Rating = null;
				}

				if (ModelState.IsValid) {
					_movies.Update(target);
				}
				else {
					ViewData["Mode"] = "EditMovie";
					ViewData["IsInvalid"] = true;
					ViewData["BodyOnly"] = true;
					ViewBag.AllRatings = GenerateRatingList(target.Rating);
					return PartialView("_MovieView", target);
				}
			}
			catch {
				ViewData["Mode"] = "EditMovie";
				ViewData["IsInvalid"] = true;
				ViewData["BodyOnly"] = true;
				ViewBag.AllRatings = GenerateRatingList(target.Rating);
				return PartialView("_MovieView", target);
			}
			ViewData["ReturnUrl"] = returnUrl;
			return PartialView(returnUrl, _movies);
		}

		public ActionResult SearchMovie(string title, DateTime? releaseDate) {
			RestClient tmdbClient = new RestClient($"{TmdbOptions.Settings.BaseUrl}");
			tmdbClient.AddDefaultHeader("Authorization", $"Bearer {TmdbOptions.Settings.BearerToken}");
			//configuration
			if (TmdbConfiguration.Settings == null) {
				IRestResponse<TmdbConfiguration> configurationResponse = tmdbClient.Execute<TmdbConfiguration>(new RestRequest($"configuration"));
				if (configurationResponse.StatusCode == System.Net.HttpStatusCode.OK) {
					TmdbConfiguration.Settings = configurationResponse.Data;
				}
			}
			//search/movie?language=en-CA&include_adult=false&region=CA&query=Red%2BDawn&year=1984
			//search/movie?language=en-CA&query=rambo&page=2&include_adult=true&region=CA&year=1980
			IRestResponse<Models.Tmdb.SearchResults> response = tmdbClient.Execute<Models.Tmdb.SearchResults>(new RestRequest($"search/movie?language=en-CA&query={title}&region=CA&year={releaseDate?.Year}"));
			SearchResults results = new SearchResults();
			if (response.StatusCode == System.Net.HttpStatusCode.OK) {
				results = response.Data;
				while (results.Page < results.TotalPages) {
					response = tmdbClient.Execute<Models.Tmdb.SearchResults>(new RestRequest($"search/movie?language=en-CA&query={title}&page={++results.Page}&region=CA&year={releaseDate?.Year}"));
					if (response.StatusCode == System.Net.HttpStatusCode.OK) {
						results.Results.AddRange(response.Data.Results);
					}
					else {
						//TODO - handle error
					}
				}
			}
			else {
				//TODO - handle error
			}
			return PartialView("_SearchResults", results);
		}

		[HttpPost]
		public ActionResult Delete(string id, string returnUrl) {
			try {
				bool result = _movies.Remove(id);
				if (!result) {
					Response.StatusCode = (int)HttpStatusCode.InternalServerError;
					return new JsonResult(new {
						message = $"Delete Failed!"
					});
				}
			}
			catch(Exception ex) {
				Response.StatusCode = (int)HttpStatusCode.InternalServerError;
				return new JsonResult(new {
					Message = $"{ex.Message}"
				});
			}
			ViewData["ReturnUrl"] = returnUrl;
			return PartialView(returnUrl, _movies);
		}

		public class AudienceRatingSelectItem {
			public string Display {
				get; private set;
			}
			public string Value {
				get; private set;
			}

			public AudienceRatingSelectItem(string noitemtext) {
				Display = noitemtext;
				Value = null;
			}

			public AudienceRatingSelectItem(AudienceRating item) {
				Display = item.Name;
				Value = item.Code;
			}
		}

		private SelectList GenerateRatingList(AudienceRating selectedItem=null) {
			//var test = new SelectListItem()
			List<AudienceRatingSelectItem> values = new List<AudienceRatingSelectItem>() {
				new AudienceRatingSelectItem("Not Selected"),
				new AudienceRatingSelectItem(AudienceRating.General),
				new AudienceRatingSelectItem(AudienceRating.Teen),
				new AudienceRatingSelectItem(AudienceRating.PG13),
				new AudienceRatingSelectItem(AudienceRating.Mature),
				new AudienceRatingSelectItem(AudienceRating.Restricted),
				new AudienceRatingSelectItem(AudienceRating.Adult),
				new AudienceRatingSelectItem(AudienceRating.Unrated)
			};
			return new SelectList(values, "Value", "Display", values.FirstOrDefault((i)=>i.Value == selectedItem?.Code));
		}
	}
}

Movie Manager UI/Views/Movie/Default.cshtml
@model MonkeyAsylum.MovieManager.Data.Models.MovieCollection
@Html.Partial("_MovieThumbnails")

Movie Manager UI/Views/Movie/_MovieDetailList.cshtml
@{
	Layout = "~/Views/Shared/_ContentLayout.cshtml";
}
@foreach (Movie item in Model) {
	<a class="text-primary text-left text-truncate text-nowrap" data-toggle="modal" data-target="#movieView" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#movieViewContent" asp-area="" asp-controller="Movie" asp-action="ViewMovie" asp-route-id="@item.Id">
		<div class="row align-items-center text-primary text-left text-truncate text-nowrap mb-2">
			<div class="col-6"><img class="d-inline-flex img-raised img-sm mr-2" src="~/cache/@item.GetThumbnail()" alt="" />@item.Title</div>
			<div class="col">Released: @item.ReleaseYear</div>
			<div class="col">Length: @item.Length</div>
			<div class="col">Rated: @(item.Rating?.Code ?? "Unknown")</div>
			<div class="col-2">Want</div>
		</div>
	</a>
}

Movie Manager UI/Views/Movie/_MovieList.cshtml
@{
	Layout = "~/Views/Shared/_ContentLayout.cshtml";
}
<div class="row">
	@foreach (Movie item in Model) {
		<div class="col-4">
			<a class="text-primary text-left text-truncate text-nowrap" data-toggle="modal" data-target="#movieView" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#movieViewContent" asp-area="" asp-controller="Movie" asp-action="ViewMovie" asp-route-id="@item.Id"><i class="fas fa-film pr-1"></i>@item.Title</a>
		</div>
	}
</div>

Movie Manager UI/Views/Movie/_MovieThumbnails.cshtml
@{
	Layout = "~/Views/Shared/_ContentLayout.cshtml";
}
<div class="row">
	@foreach (Movie item in Model) {
		<a class="" data-toggle="modal" data-target="#movieView" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#movieViewContent" asp-area="" asp-controller="Movie" asp-action="ViewMovie" asp-route-id="@item.Id">
			<img class="d-inline-flex img-raised img-xl m-2" src="~/cache/@item.GetThumbnail()" alt="@item.Title Thumbnail" />
		</a>
	}
</div>

Movie Manager UI/Views/Movie/_MovieView.cshtml
@model MonkeyAsylum.MovieManager.Data.Models.Movie

@if (!(bool)(ViewData["BodyOnly"] ?? false)) {
	<div class="modal-header">
		<h5 class="modal-title" id="title"><img class="d-inline-flex img-raised img-sm mr-2" src="~/cache/@Model.GetThumbnail()" alt="" />@(Model.Title ?? "New Movie")</h5>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
}
<div class="modal-body">
	<input id="IsInvalid" type="hidden" name="IsInvalid" value="@ViewData["IsInvalid"]" />
	<form id="movieForm" method="post" asp-controller="Movie" asp-action="@ViewData["mode"]">
		<input id="IdField" type="hidden" asp-for="Id" />
		<div class="row">
			<div class="col text-danger" asp-validation-summary="All"></div>
		</div>
		<div class="row text-primary w-100 m-1">
			<div class="col-2 justify-content-end">Title:</div>
			<div class="col justify-content-start">
				<input id="TitleField" type="text" class="form-control" asp-for="Title" />
				@*<span class="text-danger" asp-validation-for="Title" data-valmsg="*"></span>*@
			</div>
		</div>
		<div class="row text-primary w-100 m-1">
			<div class="col-2 justify-content-end">Released:</div>
			<div class="col justify-content-start">
				<input id="ReleaseDateField" type="text" class="form-control" asp-for="ReleaseDate" />
				@*<div class="invalid-tooltip" data-toggle="tooltip">invalid tooltip</div>*@
				@*<span class="text-danger" asp-validation-for="ReleaseYear"></span>*@
			</div>
		</div>
		<div class="row text-primary w-100 m-1">
			<div class="col-2 justify-content-end">Length:</div>
			<div class="col justify-content-start">
				<input id="LengthField" type="text" class="form-control" asp-for="Length" />
			</div>
		</div>
		<div class="row text-primary w-100 m-1">
			<div class="col-2 justify-content-end">Rating:</div>
			<div class="col justify-content-start">
				<select id="RatingCode" class="form-control" asp-for="Rating.Code" asp-items="@ViewBag.AllRatings" onchange="updateRating(this, event);"></select>
				<input id="RatingName" type="hidden" asp-for="Rating.Name" />
				@*@Html.EditorFor(model => model.Rating)*@
			</div>
		</div>
	</form>
	<div id="searchResults"></div>
</div>
@if (!(bool)(ViewData["BodyOnly"] ?? false)) {
<div class="modal-footer">
	<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	<button type="button" class="btn btn-secondary" onclick="movieSearch(this);">Search TMDB</button>
	@*<div id="tmdbsearch">
			<button type="button" class="btn btn-secondary" onclick="movieSearch(this);" data-toggle="popover" data-placement="bottom" data-container="#tmdbsearch" data-content="test" data-title="pop">Search TMDB</button>
		</div>*@
	@if (ViewData["mode"] == "AddMovie") {
		<button type="button" class="btn btn-primary" onclick="movieSubmit(this);">Add</button>
	}
	else {
		<button type="button" class="btn btn-primary" onclick="movieDelete(this)">Delete</button>
		<button type="button" class="btn btn-primary" onclick="movieSubmit(this)">Save changes</button>
	}
</div>
	<script type="text/javascript">
		$.validator.unobtrusive.parse('#movieForm');
		enablepops('#movieViewContent');
	</script>
}

Movie Manager UI/Views/Movie/_SearchResult.cshtml
@model MonkeyAsylum.MovieManager.UI.Models.Tmdb.SearchResult
<div class="row justify-content-center">
	<img class="d-inline-flex img-raised img-md" src="@Model.GetPosterUrl()" alt="" />
</div>
<div class="row justify-content-center">
	<h5 class="text-center" onclick="applyTmdbData(this, '#TitleField', '@Model.Title');" data-toggle="tooltip" data-placement="left" title="Click to update current record">@Model.Title</h5>
</div>
<div class="row p-2">
	<div class="col" onclick="applyTmdbData(this, '#ReleaseDateField', '@Model.ReleaseDate.ToString("yyyy-MM-dd")');" data-toggle="tooltip" data-placement="left" title="Click to update current record">Released: @Model.ReleaseDate.ToString("yyyy-MM-dd")</div>
</div>
<div class="row p-2">
	<div class="col">@Model.Overview</div>
</div>

Movie Manager UI/Views/Movie/_SearchResults.cshtml
@model MonkeyAsylum.MovieManager.UI.Models.Tmdb.SearchResults

@if ((Model?.TotalResults ?? 0) >= 1) {
	<div id="serachResultsCarousel" class="carousel slide" data-interval="false">
		@if ((Model?.TotalResults ?? 0) > 1) {
			<ol class="carousel-indicators">
				<li data-target="#serachResultsCarousel" data-slide-to="0" class="active"></li>
				@for (int i = 1; i < Model.TotalResults; i++) {
					<li data-target="#serachResultsCarousel" data-slide-to="@i"></li>
				}
			</ol>
		}
		<div class="carousel-inner" role="listbox">
			<div class="carousel-item active">
				<div class="m-4 p-2 pl-3 pr-3">
					<partial name="_SearchResult" for="Results[0]" />
				</div>
			</div>
			@for (int i = 1; i < Model.TotalResults; i++) {
				<div class="carousel-item">
					<div class="m-4 p-2 pl-3 pr-3">
						<partial name="_SearchResult" for="Results[i]" />
					</div>
				</div>
			}
		</div>
		@if ((Model?.TotalResults ?? 0) > 1) {
			<a class="carousel-control-prev" href="#serachResultsCarousel" role="button" data-slide="prev">
				<i class="now-ui-icons arrows-1_minimal-left"></i>
			</a>
			<a class="carousel-control-next" href="#serachResultsCarousel" role="button" data-slide="next">
				<i class="now-ui-icons arrows-1_minimal-right"></i>
			</a>
		}
	</div>
	<script type="text/javascript">
		enablepops("#serachResultsCarousel");
	</script>
}
else {
	<div>No Results</div>
}